export default {
  tutorialSidebar: [
    {
      type: "category",
      label: "Getting Started",
      items: [
        {
          type: "doc",
          id: "intro",
        },
      ],
    },
    {
      type: "category",
      label: "Development",
      items: [
        {
          type: "doc",
          id: "development/overview",
        },
        {
          type: "category",
          label: "Activities",
          items: [
            {
              type: "autogenerated",
              dirName: "development/activities",
            },
          ],
        },
        {
          type: "category",
          label: "Goals",
          items: [
            {
              type: "autogenerated",
              dirName: "development/goals",
            },
          ],
        },
        {
          type: "category",
          label: "VN Market Integration",
          items: [
            "development/vn-market/vn-assets-synchronization",
            {
              type: "autogenerated",
              dirName: "development/vn-market",
            },
          ],
        },
        {
          type: "category",
          label: "UI & Design",
          items: [
            {
              type: "doc",
              id: "development/ui-revamp-implementation",
            },
          ],
        },
        {
          type: "category",
          label: "Internationalization",
          items: [
            {
              type: "doc",
              id: "development/i18n",
            },
            {
              type: "doc",
              id: "development/rebranding",
            },
          ],
        },
      ],
    },

    {
      type: "category",
      label: "API Reference",
      items: [
        {
          type: "doc",
          id: "api/overview",
        },
      ],
    },
    {
      type: "category",
      label: "Deployment",
      items: [
        {
          type: "autogenerated",
          dirName: "deployment",
        },
      ],
    },
  ],
};
